# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Mathieu Chalvidal
tagline:          'Personal website'
description:      'PhD Candidate at ANITI and Brown University.' 
# Reach out on <a href="https://twitter.com/ChalviM" target="_blank">twitter</a>.'
url:              http://mathieuchal.github.io/website/
baseurl:          /

author:
  name:           'Mathieu Chalvidal'
  url:            https://twitter.com/ChalviM

paginate:         5

# Custom vars
version:          1.0.0

# github:
#   repo:           https://github.com/poole/hyde
